---
#
# Install prereq RPMs
#
- name: firewall disable | Install prerequisite RPMs
  package:
    name: yum-utils
    state: present
  when: ansible_pkg_mgr == 'yum' or ansible_pkg_mgr == 'dnf'

#
# Disable firewalld
#
- name: firewall disable | List installed firewall RPMs
  package:
    list: firewalld
  register: ipquorum_prepare_firewallrpm
  when: ansible_pkg_mgr == 'yum' or ansible_pkg_mgr == 'dnf'

- name: firewall disable | Stop and disable firewall
  service:
    name: firewalld
    state: stopped
    enabled: false
  when:
    - ipquroum_firewall_disable | bool
    - "'installed' in ipquorum_prepare_firewallrpm.results | map(attribute='yumstate') | list"