---
#
# Check If Java is already installed
#
- name: Install JavaSDK | Verify if Java is already installed
  command: which java
  register: ipquorum_install_java_task_installed
  changed_when: false
  failed_when: no

# ipquorum_install_java_task_installed.rc == 0 : installed
# ipquorum_install_java_task_installed.rc == 1 : not installed

- name: Install OpenJDK | Verify if Java is already installed - stdout Output
  changed_when: false
  debug:
    msg: "{{ ipquorum_install_java_task_installed.stdout }}"
    verbosity: 2

- name: Install OpenJDK | Verify if Java is already installed - stdout Output
  changed_when: false
  debug:
    msg: "{{ ipquorum_install_java_task_installed.rc }}"
    verbosity: 2

- block: #when rc=1
  # Copy JavaSDK file from URL
  - name: Install JavaSDK | Download Java from URL
    get_url:
      url: "{{ ipquorum_install_javasdk_src_url }}"
      dest: "{{ ipquorum_install_javasdk_download_dir }}"
      mode: 0755
      validate_certs: no
    when:
      - ipquorum_install_javasdk_src_url is defined
      - ipquorum_install_javasdk_archive_package is defined

  # Copy JavaSDK properties from local template folder
  - name: Install JavaSDK | Copy Java file from local files
    copy:
      src: "{{ ipquorum_install_javasdk_src_local }}/{{ ipquorum_install_javasdk_archive_package }}"
      dest: "{{ ipquorum_install_javasdk_download_dir }}"
      mode: 0755
    when:
      - ipquorum_install_javasdk_archive_package is defined
      - ipquorum_install_javasdk_src_url is not defined

  # Install JavaSDK from local disk
  - name: Install JavaSDK | Unpack Java SDK
    unarchive:
      src: "{{ ipquorum_install_javasdk_download_dir }}{{ ipquorum_install_javasdk_archive_package }}"
      copy: no
      dest: "{{ ipquorum_install_javasdk_install_dir }}"
      creates: "{{ ipquorum_install_javasdk_install_dir }}{{ ipquorum_install_javasdk_packages }}"

  # Set installed Java default
  - name: Install JavaSDK | Make installed Java SDK default
    command: "{{ item }}"
    with_items:
      - update-alternatives --install "/usr/bin/java" "java" "{{ ipquorum_install_javasdk_install_dir }}{{ ipquorum_install_javasdk_packages }}/bin/java" 1
      - update-alternatives --set java "{{ ipquorum_install_javasdk_install_dir }}{{ ipquorum_install_javasdk_packages }}/bin/java"
    register: ipquorum_install_javasdk_set_default

  when: ipquorum_install_java_task_installed.rc == 1