---
#
# Check If Java is already installed
#
- name: Install OpenJDK | Verify if Java is already installed
  command: which java
  register: ipquorum_install_java_task_installed
  changed_when: false
  failed_when: no

# ipquorum_install_java_task_installed.rc == 0 : installed
# ipquorum_install_java_task_installed.rc == 1 : not installed

- name: Install OpenJDK | Verify if Java is already installed and configured new - stdout Output
  changed_when: false
  debug:
    msg: "{{ ipquorum_install_java_task_installed.stdout }}"
    verbosity: 2

- name: Install OpenJDK | Verify if Java is already installed and configured new - rc Output
  changed_when: false
  debug:
    msg: "{{ ipquorum_install_java_task_installed.rc }}"
    verbosity: 2


- block: #when Java not installed.

  - name: Install OpenJDK | Ensure Java is installed.
    package:
      name: "{{ ipquorum_install_openjdk_packages }}"
      state: present
    register: openjdk_res
    retries: 5
    until: openjdk_res is success
    when:
     - ansible_os_family == 'RedHat'

  # Environment setup.
  - name: Install OpenJDK | Set JAVA_HOME if configured.
    template:
      src: java_home.sh.j2
      dest: /etc/profile.d/java_home.sh
      mode: 0644
    when: java_home is defined and java_home

  when: ipquorum_install_java_task_installed.rc == 1