---
#
# Check If Java is already installed
#
- name: Install JavaSDK | Verify if Java is already installed
  command: which java
  register: ipquorum_install_java_task_installed
  changed_when: false
  failed_when: no

# ipquorum_install_java_task_installed.rc == 0 : installed
# ipquorum_install_java_task_installed.rc == 1 : not installed
-
- name: Install OpenJDK | Verify if Java is already installed - stdout Output
  changed_when: false
  debug:
    msg: "{{ ipquorum_install_java_task_installed.stdout }}"
    verbosity: 2

- name: Install OpenJDK | Verify if Java is already installed - stdout Output
  changed_when: false
  debug:
    msg: "{{ ipquorum_install_java_task_installed.rc }}"
    verbosity: 2


- block: #When java_task_installed.rc == 1
  # Copy IBM Java file from local files folder
  - name: Install IBM Java | Copy IBM Java file from local files
    copy:
      src: "{{ ipquorum_install_javaibm_src_local }}/{{ ipquorum_install_javaibm_packages }}"
      dest: "{{ ipquorum_install_javaibm_download_dir }}"
      mode: 0755
    when:
      - ipquorum_install_javaibm_src_local is defined
      - ipquorum_install_javaibm_src_local is not defined

  # Copy IBM Java installer from URL
  - name: Install IBM Java | Download Java from URL
    get_url:
      url: "{{ ipquorum_install_javaibm_src_url }}"
      dest: "{{ ipquorum_install_javaibm_download_dir }}"
      mode: 0755
      validate_certs: no
    when: ipquorum_install_javaibm_src_url is defined

    # Copy IBM Java properties from local template folder
  - name: Install IBM Java | Copy IBM Java Properties file from local template folder
    template:
      src: javaibm.properties
      dest: "{{ ipquorum_install_javaibm_download_dir }}"
      mode: 0755

  # Problem installing the IBM Java if we dident create a export IATEMPDIR to /tmp2
  - name: Install IBM Java | Create tmp2 folder beacuse of some bullshit
    file:
      path: /tmp2
      state: directory
      mode: '0775'

  # Install IBM Java from local disk
  - name: Install IBM Java | Install IBM Java
    command: '"{{ ipquorum_install_javaibm_install_dir }}{{ ipquorum_install_javaibm_packages }}" -i silent -f /opt/javaibm.properties'
    become: yes
    environment:
      IATEMPDIR: /tmp2
    register: ipquorum_install_javaibm

  - name: Install IBM Java | Install IBM Java - Output
    changed_when: false
    debug:
      msg: "{{ ipquorum_install_javaibm.stderr }}"
      verbosity: 2

  # Set installed Java default
  - name: Install IBM Java | Make installed Java default
    command: "{{ item }}"
    with_items:
      - update-alternatives --install "/usr/bin/java" "java" "{{ ipquorum_install_javaibm_user_install_dir }}/jre/bin/java" 1
      - update-alternatives --set "java" "{{ ipquorum_install_javaibm_user_install_dir }}/jre/bin/java"
    register: ipquorum_install_java_set_default

  when: ipquorum_install_java_task_installed.rc == 1