---
#
# Copy the inn new ip_quorum.jar files from local files folder on Ansible Controller
#
- name: local ipquorum | Copy ip_quorum.jar file from local files (Uploades newer version if available)
  copy:
    src: "{{ ipquorum_local_ipquorum_app_src }}"
    dest: "/{{ipquorum_service_path}}/{{ ipquorum_service_name }}/"
  register: ipquorum_config_copy_ipquorum_local
  ignore_errors: yes
#
# Starts and Enable the IP-quorum Service.
#
- name: local ipquorum | Start and Enable IP-Quorum Service
  systemd:
    name: "{{ ipquorum_service_name }}.service"
    state: started
    enabled: yes
  register: ipquorum_config_service_enabled
#
# Restarts the the IP-quorum Service if the ip_quorum.jar is newer on local files folder.
#
- name: local ipquorum | Restart IP-Quorum Service if ip_quorum.jar is replaced
  systemd:
    name: "{{ ipquorum_service_name }}.service"
    state: restarted
    enabled: yes
  when: ipquorum_config_copy_ipquorum_local.changed and ipquorum_config_service_enabled is not changed